title: git-wiki
description: git-wiki is a jekyll theme originally based on jekyll-theme-minimal
show_downloads: true
git_branch: gh-pages
logo_url:
google_analytics:
theme: 
wiki_folder: 
use_github_wiki: true
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
